### ISSUE TITLE
general alert

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#1212]
Some other protocols have a rule to override a specific error with a generic error. It would be nice to define such a rule for TLS 1.3. For instance, `internal_error` MAY be used on any cases where a specific alert is sent.

**Comment by davidben** [comment]
internal_error is may not a great generic one, since it means something went wrong on the server's end. Though I do think we have too many alerts and can probably stand to merge some. illegal_parameter, decode_error, decrypt_error, unexpected_message, bad_record_mac, record_overflow, missing_extension, unsupported_extension all mean variations on the same thing (peer sent something invalid).

**Comment by martinthomson** [comment]
Isn't that the only thing that you ever expect to have happen?  The peer is busted?  Sure, our code has a few internal_error instances scattered around, but they are all adjacent to an assertion that crashes a debug build.

The purpose of having different types of alerts is to inform, or to at least give the recipient a clue as to where they might have gone wrong.  I don't like hard rules, because if everything were correct, we wouldn't need these alerts.  Let implementations use their own judgment in what they report and how they report it.

**Comment by tomato42** [comment]
I'm against reducing the number of alerts, they are too useful in debugging interoperability issues and testing implementations for that.

A wrong alert sent for specific errors in a message suggest a bug in the implementation; sometimes the bug is just "the wrong alert is being sent" but other times it is "a necessary check is missing". That missing check may or may not cause the implementation to be vulnerable, but it definitely requires deeper inspection.

the `internal_error` in practice should happen only in three situations: the hardware is failing (or it experienced a cosmic ray), the code is buggy but a self check detected it, or an earlier in code a necessary check is missing; neither of which is similar to any other alert

**Comment by richsalz** [comment]
Having specific alerts also brings drawbacks: it constrains implementations and it can provide information to an attacker.  I'm not arguing one way or the other, just mentioning the tension.

**Comment by davidben** [comment]
> Isn't that the only thing that you ever expect to have happen? The peer is busted?

No, not all alerts are problems in the peer. Alerts like handshake_failure, bad_certificate, etc., are not protocol errors in the peer, but cases where the two sides' preferences do not overlap. Those are worth distinguishing: they may tell administrators about a misconfiguration, or they may tell clients about a bad client certificate decision and trigger reprompts or clearing of entries in caches.

internal_error likewise is more than just debug assertions. It may happen if, say, the server is under load and wasn't able to service some signing operation. After all, HTTP 500 errors do not only happen in debug builds.

In contrast, the "peer did something wrong" alerts are much more ambiguous and much less useful. In my experience as an implementor, which to use is mostly random and up to interpretation. In particular, decode_error and illegal_parameter are essentially the same thing. RFC8446's formal syntax vs. invalid value distinction only came about after EKR and I tried to artificially construct a reason for them both to exist. In hindsight, that was a mistake and we should have merged them.

They're also very sensitive to particular implementation strategies. (Do you parse the message or check the message type first? How much is in the "parser" and how much is checked afterwards?) Because of these ambiguities, implementations, as you say, use their judgement in picking alerts. We get the worst of both worlds: the values are too coarse to usefully identify the error condition in testing or debugging, but they're fine-grained enough to still add complexity implementations and fingerprinting surface.

**Comment by tomato42** [comment]
> > Isn't that the only thing that you ever expect to have happen? The peer is busted?
> 
> In contrast, the "peer did something wrong" alerts are much more ambiguous and much less useful. In my experience as an implementor, which to use is mostly random and up to interpretation. In particular, decode_error and illegal_parameter are essentially the same thing. RFC8446's formal syntax vs. invalid value distinction only came about after EKR and I tried to artificially construct a reason for them both to exist. In hindsight, that was a mistake and we should have merged them.

I respectfully disagree. 
1. as a writer of a TLS test suite, I don't consider selected alerts to be "mostly random", if RFCs specify alerts, they are usually used consistently, there is also very little room for interpretation if you expect consistent behaviour
2. no, `decode_error` and `illegal_parameter` are not the same, they are fundamentally different. One says that the message could not be parsed according to the schema, the other says that the values in the message are invalid.
3. it's not an RFC 8446 addition, both `decode_error` and `illegal_parameter` were defined with those meanings in RFC 2246, the only thing that 8446 did, was clarify more how they should be used

while yes, which alert you'll get for a completely random message that came from a fuzzer or when through a blender depends on implementation strategy, for constructed messages, if the implementation actually implements the checks correctly, you can create messages that will consistently output one and only one alert for any implementation strategy

**Comment by davidben** [comment]
So, yes, some scenarios are unambiguous and you coherently test those scenarios. Other scenarios are ambiguous, such as getting an EncryptedExtensions with a syntax error instead of ServerHello. (Is that unexpected_message or decode_error?) And, yes, you can write tests for the unambiguous cases and accept both on the ambiguous ones.

The question is what is this test actually capturing? We care the implementation correctly rejects such-and-such invalid inputs, because that's important to the protocol working. We also care that it correctly reports "input was invalid" rather than "no ciphers in common", because that distinction is useful *outside the context of the test*.

But why might we care about `decode_error` vs `illegal_parameter`? The distinction being useful for writing tests for the distinction is meaningless. The question whether it's useful for the protocol to have different errors for these cases. My experience is no. The categories are too coarse (which field in which message of my six-message flight upset the peer?) and the ambiguous cases too common that they aren't useful for debugging. Nor would any programmatic check on the receiver care about the difference.

If complexity provides no actual benefit, we should drop it.

**Comment by davidben** [comment]
Regarding RFC8446, the new text came about when NSS was trying to use BoringSSL's test suite. EKR and I found our implementations disagreed on this alert all over the place. (It was added to the draft in September 2016 and ssl/test/PORTING.md in BoringSSL was August 2016.) We clarified it in an attempt to come up with a well-defined criteria to preserve the two alerts. The RFC5246 definitions are:

>   illegal_parameter
>      A field in the handshake was out of range or inconsistent with
>      other fields.  This message is always fatal.
>
>   decode_error
>      A message could not be decoded because some field was out of the
>      specified range or the length of the message was incorrect.  This
>      message is always fatal and should never be observed in
>      communication between proper implementations (except when messages
>      were corrupted in the network).

Note that fields being out of range is captured in both. If you had to reverse-engineer a distinction between them, you'd end up with the RFC8446 criteria. (But of course I'd think that, as I had a hand in the RFC8446 text. :-) ) But it was somewhat ambiguous before then. More importantly, it's not really useful. There are two alerts only because we tried to preserve the existence of two alerts.

**Comment by tomato42** [comment]
> So, yes, some scenarios are unambiguous and you can coherently test those scenarios. Other scenarios are ambiguous, such as getting an EncryptedExtensions with a syntax error instead of ServerHello. (Is that unexpected_message or decode_error?) And, yes, you can write tests for the unambiguous cases and accept both on the ambiguous ones.
>
> The question is what is this test actually capturing? We care the implementation correctly rejects such-and-such invalid inputs, because that's important to the protocol working. We also care that it correctly reports "input was invalid" rather than "no ciphers in common", because that distinction is useful _outside the context of the test_.

All depends on how you define "protocol working"

If you ask users, what they care for in a working implementation of TLS, they will tell you that they want it to be secure (though for majority you will most likely need to ask them what they think the lock icon represents)

Now, I think we can both agree that a "secure implementation" means one that has no vulnerabilities; one that the attacker cannot make to reveal secret data, modify secret data, refuse service to legitimate users, and can't use to elevate their privileges.

On the code level that translates to code that is _correct._ Not only code that can handle well-formed messages in expected order, one that can decrypt received messages, but one that also _correctly handles error conditions._ When we have multiple distinct error conditions, they need to be implemented as multiple separate checks. Sure, you can write them in a single `if`, but the condition will have multiple checks, not one. If as a tester I can see distinct behaviour for those checks, and I see that they behave correctly on the boundary condition, I can be reasonably sure that that check is implemented correctly. Then I can test each such check in isolation and have high confidence that the combination of all of them will behave well enough that it won't be vulnerable.

> But why might we care about `decode_error` vs `illegal_parameter`? The distinction being useful for writing tests for the distinction is meaningless. The question whether it's useful for the protocol to have different errors for these cases. My experience is no. The categories are too coarse (which field in which message of my six-message flight upset the peer?) and the ambiguous cases too common that they aren't useful for debugging. Nor would any programmatic check on the receiver care about the difference.

Does it help for interoperability? No. Does it help for debugging? Also usually no. Does it help in ensuring that the _implementations_ are secure? Yes.

While you can argue that security of implementations is not something that standards should care about. How easy it is to implement _and verify_ that an implementation is secure is something that end users of those standards care about. Thirty years of RSA PKCS#1 vulnerabilities show what happens if that is not a consideration.

(side note: I don't think fully parsing a message and only then checking if the type of it matches the expected type is a good idea, I can see it helping the attacker exploit bugs in parsers, especially for features that must be negotiated or manually enabled)

**Comment by davidben** [comment]
There's no need to act like I don't know about testing or error conditions. Between tlsfuzzer and BoringSSL's test suite, I think you and I have both spent plenty of time thinking about testing TLS. :-)

Of course the way to test security-critical error conditions is by isolating it in a test. But the alert isn't part of the security requirement, and, when testing, the alert doesn't isolate the error: TLS's alert codes match large classes of errors. The way to isolate it is for the test input to only include one error, with other properties correct. If you've done that, you've isolated it. If you haven't, there is a bug in the test.

Alerts and implementation-specific error codes _are_ useful to check that you've successfully constructed the test, and indeed we assert on both in BoringSSL's test suite. But this is merely a _rough_ check of the correctness of the _test_. It's not about the implementation, nor is it the only way to get confidence in your test. (You can have a control run without the error that should succeed. You can temporarily intentionally break an implementation and make sure your test notices. You can test the output of your testing framework to make sure it doesn't change unexpectedly.)

That means this should be an opportunistic thing, not a requirement: if it's otherwise harmless, sure, use different errors and tests can get a marginal confidence boost. But this one's not harmless. It adds complexity to implementations who need to use different codepaths for some encoding errors vs. others. It more ambiguous cases to the specification, since sometimes multiple alerts apply. It adds fingerprinting vectors because there are now multiple ways to resolve an ambiguity. (Analogously, it would be convenient for testing if error cases in PKCS#1 padding had different error codes. But there are security requirements not to do that. Yet we still can and do isolate parts of PKCS#1 padding in tests.)

This is also our strategy with BoringSSL's test suite. We'll happily assert on the internal error code, which are even more fine-grained than alerts. But if we end up folding error codes together or shifting them around, we update the test without a second thought because they're not the important part.

**Comment by richsalz** [comment]
Fine-grained alerts can help with showing the code is correct, but it's outweighed by:
- Fuzzers
- The fact that they constrain the implementation

**Comment by tomato42** [comment]
@davidben I can only say that it's not my experience, I find that specific errors help in correctness of both implementation and test cases, not just as a "rough check of the test". While in many cases you can create complex reproducers that test all the corner cases without looking at alerts, without specific alerts it's _harder,_ not easier.
Yes, original handling of PKCS#1 errors was incorrect on protocol level, the later versions fixed that. So if you want to fix issues like ROBOT you need to strictly follow the alert requirements.
I don't think that "increasing the complexity of the implementation" is a valid argument when the differences we talk about are semantically between
```
if not valid_format(msg, ENCRYPTED_EXTENSIONS) || not consistent_values(msg, client_hello, server_hello):
   send_fatal_alert(GENERIC_ALERT)
```
and
```
if not valid_format(msg, ENCRYPTED_EXTENSIONS):
   send_fatal_alert(DECODE_ERROR)
if not consistent_values(msg, client_hello, server_hello):
   send_fatal_alert(ILLEGAL_PARAMETER)
```

> @richsalz
> Fine-grained alerts can help with showing the code is correct, but it's outweighed by:
> 
>     * Fuzzers

Which fuzzers actually check the alerts sent by the other side of the connection? For which ones specific alerts are a problem, and why?

>     * The fact that they constrain the implementation

how's that a bad thing?

**Comment by richsalz** [comment]
> Which fuzzers actually check the alerts sent by the other side of the connection? For which ones specific alerts are a problem, and why?

Fuzzers are also good at showing the code works with bad input.  Checking for specific alerts does some of that, but in my view fuzzers are better at finding more instances of wrong input being handled.

Specific alerts also limits how the code is implemented.  That is an onerous burden, especially when you consider non-C/C++ languages. I see that as a bad thing, I guess you see it as not bad.  Shrug, it's a matter of opinion.  I guess my opinion is informed be seeing "needless" bug reports against OpenSSL because the "wrong" alert was sent.

I could imagine an implementation that parsed and verified things in a streaming manner, and would just throw an exception if anything went wrong without caring about details.

**Comment by tomato42** [comment]
> > Which fuzzers actually check the alerts sent by the other side of the connection? For which ones specific alerts are a problem, and why?
> 
> Fuzzers are also good at showing the code works with bad input. Checking for specific alerts does some of that, but in my view fuzzers are better at finding more instances of wrong input being handled.

you didn't say how that is problematic to fuzzers
 
> Specific alerts also limits how the code is implemented. That is an onerous burden, especially when you consider non-C/C++ languages. I see that as a bad thing, I guess you see it as not bad. 

then please explain why it's a burden

> Shrug, it's a matter of opinion. I guess my opinion is informed be seeing "needless" bug reports against OpenSSL because the "wrong" alert was sent.

and mine in informed by finding security issues; and by working regularly with 4 different implementations
and from my point of view 20 "needless" bugs are a small price to pay for one CVE
but I guess I care too much about security of the TLS implementations and too little about having dozens upon dozens of TLS implementations

> I could imagine an implementation that parsed and verified things in a streaming manner, and would just throw an exception if anything went wrong without caring about details.

and I can't imagine how throwing a specific exception in such streaming implementation is an insurmountable burden

**Comment by richsalz** [comment]
I don't have anything worthwhile to add.  We bring different sets of experiences; you like specfic alerts, I don't.

**Comment by chris-wood** [comment]
Discussed in 110: Encourage specificity, but allow a general alert.
