### ISSUE TITLE
A mechanism is needed to indicate that a session will not be resumed

### ISSUE THREAD

**Issue by briansmith** [tlswg/tls13-spec#137]
1. If the client has session resumption disabled, then it should be able to tell the server this, so that the server doesn't cache the master secret.

2. If the server has decided not to cache the session, then the server should tell the client this, so that the client doesn't cache the master secret.

3. Optionally, either side should be able to announce this at any time during the connection. However, it may be acceptable to just have these indications in ClientHello and ServerHello extensions.

By throwing away the master secret ASAP, the confidentiality of the connection is protected.

Although I worded this issue in terms of traditional session resumption, the same considerations apply to anything that requires the client or server to hold onto the master secret after the handshake is complete.

**Comment by ekr** [comment]
Note that the current key hierarchy divorces the MS used to generate the traffic keys
from the RMS used to resume the session, so storing the RMS doesn't impact the
security of the connection that initiated the connection.

It might still be worthwhile to have subsequent connections be able to announce this,
but I'm not sure how practical that is in the case of tickets since as long as the
ticket key exists, deleting the ticket store doesn't help much.

**Comment by grubba** [comment]
Regarding point 2: The server is already able to do this via sending an empty session_id in the ServerHello. cf RFC 5246 7.4.1.3:

    The server may return an empty session_id to indicate that the session will not be cached
    and therefore cannot be resumed.

**Comment by ekr** [comment]
At this point, the server can opt not to allow resumption by simply not sending a new session ticket.
The client cannot tell the server not to send it, but this is merely saving cost to the server because the Resumption Master Secret (which is what is attached to the session) does not allow you to decrypt the connection. My sense is that list consensus did not support a change here.

If you want to pursue this, please take it to the list.
