### ISSUE TITLE
Consider combining Certificate+CertificateVerify

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#212]
They always appear together anyway.  Having them independently optional risks errors.  And combining them will save a few bytes from the handshake.

The separation might have been nice in a past where static (EC)DH cipher suites were in use, but I don't see any way of TLS 1.3 supporting those modes in the future once we accept #211.

**Comment by martinthomson** [comment]
Ilari notes:

    Also, regarding issue #212, unless the Certificate is handled specially,
    it would mean that the signature does not cover certificate. And not
    signing the certificate (esp. the public key within) causes problems
    in some exotic cases (I don't know if any of those cases pop up in TLS
    1.3).

**Comment by davegarrett** [comment]
Ilari's point is quite a good one, and unless you can elaborate on a known risk that's particularly important, I don't see it outweighing the need to touch this area. I think Certificate, CertificateVerify, & Finished all need to be separate, because the latter two each depend on a hash of the session prior to it and I think the safest route is to just keep this design as-is.

Handshake messages are coalesced into a single record, so merging two only saves 4 bytes, which I don't think is worth worrying about once per handshake.

**Comment by ekr** [comment]
I think the conclusion is that this was a bad idea.
