### ISSUE TITLE
Use "raw public keys" instead of DH_anon?

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#233]

**Comment by davegarrett** [comment]
Just posting this link here, too. This is the "Unauthenticated Cipher Suites" section I put together for my old a la carte proposal. I had already made note of raw public keys in it, so here it is cut out, as it's already done and usable with almost no changes needed. If the decision is to completely deprecate DH_anon as well as note raw key use, then some minor changes to this are needed.
https://github.com/davegarrett/tls13-spec/commit/17a884c9c53658258eb3abe9777b1cd76e9d5064

Not a PR or otherwise a complete proposed solution; just an existing section that I had on hand that can serve as a starting point, if desired.

**Comment by beurdouche** [comment]
https://github.com/beurdouche/tls13-spec/tree/patch_anonDH_removal
takes that commit and makes small progress...

**Comment by ekr** [comment]
Consensus at interim: make this change. @beurdouche I will review this PR
