### ISSUE TITLE
rendering discrepancy; indented references not linkified

### ISSUE THREAD

**Issue by davegarrett** [tlswg/tls13-spec#247]
There's a rendering discrepancy between the editor's copy & working group draft. Within indented sections, bracketed links are not linkified in the github.io version but are in the final version that ends up on ietf.org. See the cipher suite and contributors sections:

https://tlswg.github.io/tls13-spec/#cipher-suites
https://tools.ietf.org/html/draft-ietf-tls-tls13-08#appendix-A.4

https://tlswg.github.io/tls13-spec/#rfc.appendix.F
https://tools.ietf.org/html/draft-ietf-tls-tls13-08#appendix-F

If these two differ in a substantial way, it makes catching issues that break one but not the other a bit difficult.

**Comment by martinthomson** [comment]
That is a shortcoming of the kramdown tool, which doesn't recognize those as references correctly.  That can be corrected by using a strict reference form `{{I-D.reference}}` rather than square brackets.  However, it looks like the contributors section is not a list, but a diagram, so that might not work there either.

Converting the cipher suites section to a table would work, but the kramdown syntax for that is horrific.  Converting the contributors section to a list would address the problem, but that might be a little difficult to do properly.

Note that the links on the html-ized tools version is generated from the plaintext, so all it has to go on are the square brackets.

**Comment by davegarrett** [comment]
On Thursday, September 17, 2015 02:52:31 pm Martin Thomson wrote:
> That is a shortcoming of the kramdown tool, which doesn't recognize those as references correctly.

Can this be reported upstream then, or is this already known there?

**Comment by martinthomson** [comment]
I would think that you should try to fix this by changing to using tables and lists rather than diagrams.  The kramdown tool can't be expected to extract references from artwork.  It wouldn't have anywhere to put the references in the XML format even if it did.

You could also decide that this isn't important enough to bother fixing.

**Comment by davegarrett** [comment]
On Thursday, September 17, 2015 03:40:30 pm Martin Thomson wrote:
> I would think that you should try to fix this by changing to using tables and lists rather than diagrams.  The kramdown tool can't be expected to extract references from artwork.  It wouldn't have anywhere to put the references in the XML format even if it did.

Isn't there just some way to indent some text without it being treated as "artwork"? If not, that's rather silly.

> You could also decide that this isn't important enough to bother fixing.

If there's no simple fix, then yeah, I'll just close this as wontfix.

**Comment by martinthomson** [comment]
Indenting is easy:  http://kramdown.gettalong.org/syntax.html#blockquotes

Tables are relatively easy too: http://kramdown.gettalong.org/syntax.html#tables

**Comment by ekr** [comment]
If someone wants to provide a PR, I'll take a fix for this, but since it doesn't apply to the final RFC, I'm going to backburner it.

**Comment by davegarrett** [comment]
This is fixed now. Both renderings now linkify properly with recent changes from @martinthomson. There's actually quite a bit more difference between the two renderings, but this issue, the noted reference linkification, is fixed. Closing.
