### ISSUE TITLE
CELLOS: HelloRetryRequest

### ISSUE THREAD

**Issue by seanturner** [tlswg/tls13-spec#302]
Seems not necessary.

**Comment by ekr** [comment]
It is definitely necessary because the client may be wrong about which groups the server supports. I'm closing this, but feel free to re-open if you have a more detailed explanation.

**Comment by davegarrett** [comment]
There is an alternative to HelloRetryRequest: require all clients offer keys for all of their supported groups. Probably not desired, thus the retry mechanism. Alternatively, make this a "SHOULD" or "RECOMMENDED" and have a clear "unsupported_groups" alert that MUST be returned the instant group negotiation fails, after which point the client then MUST send its full set of possible keys. This provides the same sort of mechanism, but with just the one simple signal instead of a new message (both unauthenticated).

**Comment by ekr** [comment]
I don't believe that either of these are good options, especially since we need
a mechanism like this in any case for DTLS anti-DoS

@martinthomson, @beurdouche, Karthik, and I have worked out what we believe
is a good answer for this entire class of issues which I'll be posting next week.
