### ISSUE TITLE
Improve ECC security, move to non NIST curves.

### ISSUE THREAD

**Issue by fefafefa** [tlswg/tls13-spec#401]
Dear TLS1.3 spec. staff.

There are a lot of curves that are well implemented and full documented, not like the NIST curves [https://safecurves.cr.yp.to/].
Please, consider to use, or at least support, non NIST curves.

We can improve the security of the web, using open and strong ECC in our communications!  :)
Curve25519 [State: Mature.]
Ed448-Goldilocks  [State: Mature.]
E-521 [State: New.]

Thanks for your time.

Making the web secure.

Best regards.

Fefafefa.

**Comment by davegarrett** [comment]
https://tools.ietf.org/html/draft-ietf-tls-tls13-11#page-51

25519 & 448 are already listed in the current draft, for both ECDHE & signatures. X25519 (CRFG's document) is listed in the MTI section as a "SHOULD" support for key exchange alongside P-256 which is at "MUST" level support, due to its already widespread adoption.

I suggest reading the current draft in full, as well as mailing list discussions on this topic. New proposals are better posted to the list with details, rather than here.

**Comment by ekr** [comment]
Already fixed.
