### ISSUE TITLE
With resumption PSK, make the PSK label partly derived from the session hash

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#427]
E.g.,
Label = Session_Hash + NewSessionTicket.ticket.

This binds HS1 to HS2 more tightly.

**Comment by martinthomson** [comment]
This seems reasonable.  I think, however, that this assumes a ticket-based scheme; where the resumption MS is somehow encrypted into the ticket value.  Two servers doing stateful resumption could generate the same value for NewSessionTicket.ticket with non-trivial probability.

**Comment by ekr** [comment]
I'm not following. Right now the resumptions of those handshakes will have psk_label the same. This will make them different.

**Comment by martinthomson** [comment]
I misunderstood your suggestion then.  

Are you suggesting that the key derivation for HS2 include the ticket identifier (my initial assumption). or that the construction of the resumption master secret needs to take NewSessionTicket as input?  Because I don't see how the latter is compatible with having NewSessionTicket constructed at arbitrary times.

BTW, we should try to align `psk_identity` with `NewSessionTicket.ticket`

**Comment by ekr** [comment]
Right now psk_identity == NewSessionTicket.ticket (at least that's what I think the spec says and that's how Karthik and I both implemented)

What Karthik is suggesting is something like:
1. NewSessionTicket.ticket == T, which is some value which allows the server to recover (RMS, SessionHash)
2. psk_identity = Hash(SessionHash) || T [Hash()] may be unnecessary
3. The server uses T to recover RMS, SessionHash (and probably verifies Hash(SessionHash))

We should discuss on-list. I just made the issue so I didn't forget.

**Comment by martinthomson** [comment]
OK, then yes.  I would recommend a new field rather than concatenating.  And maybe just export something unless transitively including the session hash is problematic for any reason.

Now you can't forget the actual details.
