### ISSUE TITLE
Relax server-side KeyShareEntry checking

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#473]
Clients MUST NOT offer multiple KeyShareEntry values for the same parameters.
Clients and servers MUST NOT offer any KeyShareEntry values for groups not
listed in the client's "supported_groups" extension.
Servers MUST NOT offer a KeyShareEntry value for a group not offered by the
client in its corresponding KeyShare.
Implementations receiving any KeyShare containing any of these prohibited
values MUST abort the connection with a fatal "illegal_parameter" alert.

It's a pain in the ass to check for KeyShareEntry values that are not in the NamedGroups and NSS doesn't presently do it. I think the requirement should be relaxed to just be that you don't select one of them.

**Comment by ekr** [comment]
@davegarrett I think you wrote this text. Objections?

**Comment by davegarrett** [comment]
Relaxing this a bit should be fine. Letting redundant keys slide sounds a bit risky for interop, though. PR with new text submitted.

**Comment by davegarrett** [comment]
The "MUST" for what error to throw could be reduced to a "SHOULD", if you'd like to make this even less strict. Not likely to come up that often, though, and I don't see it being more than an interop & waste issue (at least at the moment).

**Comment by martinthomson** [comment]
I think that MUST NOT send and MAY generate a fatal error is the right balance here.  As an implementation, it's annoying to do this sort of validation because you have to cross validate two extensions, and most of the code for extensions is in the extension handler.

Note that even the check for duplicate groups is not something that NSS does.

(Did you want to close this now?)
