### ISSUE TITLE
Cookie-only HelloRetryRequest doesn't quite work right

### ISSUE THREAD

**Issue by davidben** [tlswg/tls13-spec#560]
This was mentioned at the hackathon, but I forgot to file a bug. The server may send a HelloRetryRequest if it needs a key_share AND/OR if it wants a cookie to prove reachability. If only the cookie, this part of the spec can't be followed:

> Upon receipt of a HelloRetryRequest, the client MUST first verify that the selected_group field corresponds to a group which was provided in the “supported_groups” extension in the original ClientHello. It MUST then verify that the selected_group field does not correspond to a group which was provided in the “key_share” extension in the original ClientHello.

Relatedly, if the server selected a pure PSK cipher but still needed to assert a cookie, it can't send a HelloRetryRequest without requesting a key share.

Simplest fix would probably be to move key_share to the extensions field, since it otherwise is an extension anyway. Though the `select (role)` needs now three cases, so it's a little screwy. Then the text can say something like "if there is a key_share extension present, the client MUST first verify, etc.". It may or may not also be worth saying something like "servers MUST NOT send HelloRetryRequest without any extensions".

**Comment by ekr** [comment]
Yeah, I noticed this the other day too. 

Not sure about your fix. Why not just say that if you sent a share in the group you take the cookie and move on

**Comment by davidben** [comment]
How would you handle pure PSK ciphers where you don't pick a group at all?

**Comment by ekr** [comment]
Yeah, fair point. I'll have to think about that.

**Comment by hannestschofenig** [comment]
I would change the structure of the HelloRetryRequest message 

FROM:

struct {
       ProtocolVersion server_version;
       CipherSuite cipher_suite;
       NamedGroup selected_group;
       Extension extensions<0..2^16-1>;
   } HelloRetryRequest;

TO:

struct {
       ProtocolVersion server_version;
       CipherSuite cipher_suite;
       Extension extensions<0..2^16-1>;
   } HelloRetryRequest;

and put the selected_group in the extension part. Then, if the client only used a PSK cipher without any ECDHE then it will not provide a selected_group extension in the ClientHello and the server does not need to include it in the HelloRetryRequest either. 

On the other hand, you are not likely going to send a HelloRetryRequest when you are using a pure PSK-based ciphersuite since the error condition of the server not finding an acceptable set of algorithms and groups that are mutually supported is not going to occur. The use of the  HelloRetryRequest for DoS protection is only mentioned as a side remark and I believe it was introduced for unreliable transports rather than for TLS over TCP.

I prefer the former approach since it makes our life easier when we define DTLS 1.3 where the HelloRetryRequest message makes sense for testing reachability.

**Comment by davidben** [comment]
Yeah, this is my proposal as well (moving to an extension). I think it came up on the list as well. Then we say that an HRR MUST have at least one extension.

Note though that the cookie use case will someday run into other troubles with HelloRetryRequest. You need all the information for HelloRetryRequest fit in the first packet of ClientHello. We're fine now, but the ClientHello is getting larger and larger. It suggests that the cookie use case really should be handled by something at the "transport" layer, to mirror the TCP case. (By "transport", I mean the layer just under the handshake. DTLS isn't quite so clearly layered like this, but I'm of course largely thinking QUIC.)

E.g. you could imagine that every packet in the initial flight were tagged with some kind of source address token rather than doing it at the message level.

**Comment by ekr** [comment]
@davidben, @hannestschofenig patch welcome

**Comment by ekr** [comment]
This is fixed in @davidben's new PR.
