### ISSUE TITLE
No point in Finished for rejected post-handshake auth

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls13-spec#572]
> If it declines, it MUST send a Certificate message containing no certificates followed by Finished.

If the client declines to authenticate, the empty Certificate message is all that is necessary.  Retaining Finished keeps the form compatible with the initial handshake, but it serves no real purpose post-handshake.

**Comment by ekr** [comment]
It may not be a good idea, but it's not correct that it serves no purpose, because there is partial key separation. Therefore it's possible that if (for instance) the actual working keys were compromised the Finished keys would not be, and thus you would have authenticated assurance that the other side did intend to send you an unauthenticated Finished.

**Comment by ekr** [comment]
I am going to mark this as closed. Please feel free to reraise on the list if you care.
