### ISSUE TITLE
PSK binder validation and fallback

### ISSUE THREAD

**Issue by kazu-yamamoto** [tlswg/tls13-spec#836]
Section 4.2.8. says:

> Prior to accepting PSK key establishment, the server MUST validate the corresponding binder value (see Section 4.2.8.1 below). If this value is not present or does not validate, the server MUST abort the handshake. 

Are there any reasons to not allow fall back to full handshake if binder value is not present or does not validate?

**Comment by kazu-yamamoto** [comment]
If "the handshake" means "selecting the PSK", not the entire handshake, I would suggest to change the wording.

**Comment by ekr** [comment]
I'm not sure why you would want to allow it. There's no legitimate reason for a binder to be invalid.

**Comment by kazu-yamamoto** [comment]
Suppose there is one pair of PSK and its binder. If the binder is invalid, I want to fallback to full handshake. But this sentence reads that the server must abort the entire handshake in that case.

**Comment by davidben** [comment]
Why? Implementations aren't expected to fallback to full handshake if early data can't be decrypted, which is a similar sort of thing. If a PSK can't be resumed because some configuration or state changed and it's no longer valid, you want to fallback. If it can't be resumed because the client doesn't appear to have possession of the PSK, a hard error is reasonable.

Making this a fatal error means it's less likely that interop errors in computing the binder will get masked.

**Comment by kazu-yamamoto** [comment]
OK. Make sense. It would be nice if such conditions for fallback are explicitly described in the draft.

**Comment by ekr** [comment]
@kazu-yamamoto: PR welcome

**Comment by kazu-yamamoto** [comment]
Let's close this issue in favor of #893.
