### ISSUE TITLE
Require SNI

### ISSUE THREAD

**Issue by ekr** [tlswg/tls13-spec#839]
I'm pretty confident we had consensus to require SNI but the current text just says that it's MTI, not mandatory to send if you had it. I believe that this is just editor error, but this is an issue to prompt me to go back and check the list.

**Comment by martinthomson** [comment]
"MUST use" or "MUST implement"?  There are some of uses of TLS that don't require SNI for various reasons.  Many of those identify based on key/cert rather than name, for example.

Requiring SNI for HTTPS makes perfect sense.  The same probably applies to a bunch of other protocols, but it might be hard to mandate use more broadly.

The hazard here is that where SNI is used, it needs to be checked.  Servers that accept SNI and ignore the value cause themselves (and others) problems.

**Comment by ekr** [comment]
@davegarrett: do you recall?

**Comment by davegarrett** [comment]
Near as I can remember, we did settle on MUST implement, SHOULD use when applicable, and that servers MAY REQUIRE its use. However, if a system is specifically designed in a manner that has no need for SNI, for whatever reason, we don't need to compel them to leak information if they don't actually need to. I know the HTTP/2 spec does explicitly require SNI [0], and leaving this up to the application layer seems reasonable.

I don't think we've had any discussion about what to do with a server that receives SNI but doesn't strictly require it. Adding a new requirement that all servers receiving SNI MUST validate that it is applicable also seems reasonable, but discussing it on list is probably warranted.

[0] https://tools.ietf.org/html/rfc7540#section-9.2

**Comment by ekr** [comment]
@davegarrett: I'm not sure I love this requirement, but feel free to raise this on the list.
