### ISSUE TITLE
question about 32-bit signature prefix attack

### ISSUE THREAD

**Issue by mimoo** [tlswg/tls13-spec#849]
> This structure is intended to prevent an attack on previous versions of TLS in which the ServerKeyExchange format meant that attackers could obtain a signature of a message with a chosen, 32-byte prefix. The initial 64 byte pad clears that prefix.

From the spec. There is no reference here. I'm wondering what attack it is.

**Comment by martinthomson** [comment]
There doesn't need to be a concrete attack.  The point is that a client can obtain a signature on 32 bytes of its choosing (the ClientHello.random), plus some stuff that it doesn't control.  In the right circumstances, that could be a problem.  For TLS 1.3, padding out the prefix means that a TLS 1.3 signature cannot be exchanged for a TLS <=1.2 signature.

**Comment by mimoo** [comment]
Thanks for that answer! Any reason the padding is 64 byte instead of 32 byte then?

**Comment by davidben** [comment]
There's a 32-byte ServerHello.random after the ClientHello.random. We want to clear both of them.

**Comment by mimoo** [comment]
Ah. In case the attacker would be the server. Ok I see thanks!

**Comment by mimoo** [comment]
Actually, that doesn't make sense, because the server can sign anything anyway. Now I'm back to not understanding why we would want to clear the ServerHello.random

**Comment by davidben** [comment]
Hrm. Yeah, actually I can't see a concrete attack either if we don't clear ServerHello.random. An attacker trying to collide a TLS 1.2 signature can just echo back whatever ServerHello.random ends up in there. If TLS 1.2 client certificates had the same construction, we would want to clear it, but clients sign the handshake transcript in TLS 1.2. It's just the server half we got wrong.

**Comment by davidben** [comment]
Oh! This gives you a guarantee that the converse can't happen. A TLS 1.2 ServerKeyExchange signature can't be used in any TLS 1.3 context because the server will always pick a fresh ServerHello.random, which has low probability of matching the spaces. For that direction, clearing ClientHello.random doesn't work because I can send any ClientHello.random I want for the server to sign.

(The server-selected ServerHello.random also has low probability of matching the context string, but then we depend on the length on the context string and whatnot.)
